env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  ChromaDB {
    url = "http://localhost:8000"
    collections = ["test_chromadb_migration"]
    batch_size = 1000
  }
}

sink {
  Milvus {
    url = "http://localhost:19530"
    token = ""
    database = "default"
    schema_save_mode = "RECREATE_SCHEMA"
    data_save_mode = "APPEND_DATA"
  }
}
